// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx004l-plEITr5cZA6HJ8CYawlpKKy96g',
    appId: '1:411099512667:web:dc43c9bfb8a6cb750fe47e',
    messagingSenderId: '411099512667',
    projectId: 'fitnessapp-292ab',
    authDomain: 'fitnessapp-292ab.firebaseapp.com',
    databaseURL: 'https://fitnessapp-292ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitnessapp-292ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8N0z86HVlBRw9y_F4nUTakugLewF1pSA',
    appId: '1:411099512667:android:e0ec01dafc97a4a00fe47e',
    messagingSenderId: '411099512667',
    projectId: 'fitnessapp-292ab',
    databaseURL: 'https://fitnessapp-292ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitnessapp-292ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8GQZTz43B0Eeb4IKTGcCHWUbeaHmy8A',
    appId: '1:411099512667:ios:a8446c433d8de05e0fe47e',
    messagingSenderId: '411099512667',
    projectId: 'fitnessapp-292ab',
    databaseURL: 'https://fitnessapp-292ab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fitnessapp-292ab.appspot.com',
    androidClientId: '411099512667-2c4uioq6flpdpvdlqk31g0hamj7e477p.apps.googleusercontent.com',
    iosClientId: '411099512667-c5c35e4f6fg9dclca64gbou2kv669s6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
